### ISSUE TITLE
make: *** [Makefile.coq] Error 1

### ISSUE THREAD

**Issue by isutare412** [snu-sf-class/pl2016#10]
If i type "make" in 00 directory to compile codes, the error occurs.

This is error by `make`
`(echo "-R . assignment"; \
         echo D.v P01.v P02.v P03.v E01.v E02.v E03.v) > _CoqProject
coq_makefile -f _CoqProject -o Makefile.coq`

then, next two error lines occur.
`make: coq_makefile: No such file or directory`
`make:*** [Makefile.coq] Error 1`

I do not understand why errors occur.

**Comment by isutare412** [comment]
Solved the problem!
`D.v` must be compiled into `D.vo` in order to be exported in another .v files.
So, I opened `D.v` and compiled the buffer. Now with `D.vo` in the same directory, P01.v works well.

**Comment by jeehoonkang** [comment]
Dear @isutare412 ,

I think you really have to be able to compile by `make`, since there will be a lot of assignment files later.  Your error message says `coq_makefile` is not in the `PATH`.
- Check the `PATH` variable by `env`, and see if it has the directory that contains `coq_makefile`.
- Type `which coq_makefile` to see if there is one.

**Comment by jeehoonkang** [comment]
Duplicate https://github.com/snu-sf-class/pl2016/issues/15
